#!/usr/bin/env bash
# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

install_thoughtbot() {
  fancy_echo() {
    local fmt="$1"; shift

    # shellcheck disable=SC2059
    printf "\\n$fmt\\n" "$@"
  }

  append_to_zshrc() {
    local text="$1" zshrc
    local skip_new_line="${2:-0}"

    if [ -w "$HOME/.zshrc.local" ]; then
      zshrc="$HOME/.zshrc.local"
    else
      zshrc="$HOME/.zshrc"
    fi

    if ! grep -Fqs "$text" "$zshrc"; then
      if [ "$skip_new_line" -eq 1 ]; then
        printf "%s\\n" "$text" >> "$zshrc"
      else
        printf "\\n%s\\n" "$text" >> "$zshrc"
      fi
    fi
  }

  # shellcheck disable=SC2154
  trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

  set -e

  if [ ! -d "$HOME/.bin/" ]; then
    mkdir "$HOME/.bin"
  fi

  if [ ! -f "$HOME/.zshrc" ]; then
    touch "$HOME/.zshrc"
  fi

  # shellcheck disable=SC2016
  append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

  gem_install_or_update() {
    if gem list "$1" --installed > /dev/null; then
      gem update "$@"
    else
      gem install "$@"
    fi
  }
  
  # Install basic dotfiles
  if [ -d "$HOME/.dotfiles" ]; then
    cd "$HOME/.dotfiles"
    git pull
    cd "$HOME/.dotfiles-local"
    git pull
  else
    # Clone dotfiles
    git clone git://github.com/thoughtbot/dotfiles.git "$HOME/.dotfiles"
    git clone https://github.com/execat/dotfiles-local.git "$HOME/.dotfiles-local"

    # Install RCM for linking dotfiles
    sudo add-apt-repository ppa:martin-frost/thoughtbot-rcm
    sudo apt update
    sudo apt install rcm
  fi

  env RCRC=$HOME/.dotfiles/rcrc rcup
  rcup
}

install_apt() {
  sudo apt install fasd tree git-extras git-flow elixir emacs neovim cloc howdoi wget
  sudo add-apt-repository ppa:webupd8team/java
  sudo apt install oracle-java8-installer

  # All utils
  sudo apt install bash cowsay findutils mlocate moreutils binutils diffutils
  sudo apt install -y libssl-dev libreadline-dev zlib1g-dev # For Ruby
  sudo apt install python3-dev python3-pip
  sudo pip3 install thefuck
}

install_packages() {
  if [ ! -d "$HOME/.fzf" ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
  fi

  if [ ! -d "$HOME/.rbenv" ]; then
    export PATH="$HOME/.bin:$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
    git clone https://github.com/rbenv/rbenv.git ~/.rbenv
    ~/.rbenv/bin/rbenv init || true
    mkdir -p "$(rbenv root)"/plugins
    git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
    git clone https://github.com/rbenv/rbenv-default-gems.git $(rbenv root)/plugins/rbenv-default-gems
    cat > ~/.rbenv/default-gems <<EOF
bundler
pry
activesupport
EOF
  fi
}

install_binaries() {
  # Check their GitHub: https://github.com/thisredone/rb
  curl https://raw.githubusercontent.com/thisredone/rb/master/rb -o ~/.bin/rb && chmod a+x ~/.bin/rb
}

run_script() {
  rbenv init || true
  rbenv install jruby-9.2.0.0
  rbenv install 2.5.3
  rbenv global 2.5.3
  mkdir -p _code
}

# Install ohmyzsh
install_ohmyzsh() {
  if [ -d "$HOME/.oh-my-zsh" ]; then
    cd "$HOME/.oh-my-zsh"
    git pull
  else
    # Do entire oh-my-zsh installation but don't drop in the Zsh session (last line of the script)
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | grep -v 'env zsh')"
    git clone https://github.com/MichaelAquilina/zsh-you-should-use.git $HOME/.oh-my-zsh/custom/plugins/you-should-use
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    chmod g-w,o-w ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

    echo "Now customizing zsh setup"
    # Change theme (remove '' if not on macOS)
    # sed -i "s/robbyrussell/af-magic/g" ~/.zshrc
    sed -i "s/robbyrussell/af-magic/g" ~/.zshrc
    cat >> ~/.zshrc <<EOF

# Local config
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# aliases
[[ -f ~/.aliases ]] && source ~/.aliases

eval "$(rbenv init -)" +

export PATH="$HOME/.bin:$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
EOF
  fi
  
  # Use .dotfiles and .dotfiles-local to create aliases
  rcup -d .dotfiles -d .dotfiles-local
}

# Install SpaceVim for neovim
install_spacevim() {
  if [ -d "$HOME/.SpaceVim" ]; then
    cd "$HOME/.SpaceVim"
    git pull
  else
    curl -sLf https://spacevim.org/install.sh | bash -s -- --install neovim
    sudo pip3 install neovim
    nvim

    if [ -d "$HOME/.SpaceVim.d" ]; then
      echo "Moving init.toml"
      mv ~/.SpaceVim.d/init.toml{,.bak}
      cat > ~/.SpaceVim.d/init.vim <<EOF
let g:spacevim_plugin_bundle_dir = '~/.cache/vimfiles/'
call SpaceVim#layers#load('lang#ruby')
call SpaceVim#layers#load('ctrlp')
call SpaceVim#layers#load('shell')

let g:spacevim_custom_plugins = [
      \ ['sotte/presenting.vim'],
      \ ]

set clipboard+=unnamedplus

" Use the arrows to something usefull
map <right> :bn<CR>
map <left> :bp<CR>

" Close all the buffers
map <leader>ba :1,300 bd!<CR>

set wrap
EOF
    else
      echo "Folder not found"
    fi
  fi
}

show_final_messages() {
  cat << END
  Go to Trackpad and uncheck and check the "Tap to click" and "Secondary click" option.
  Also move click to "light" and turn on silent clicking.

  Also do these things manually:
  1. Set up .ssh keys (copy or create new)
  2. Start jdiskreport and run mlocate
  3. Set up keyboards for your preferred languages and layouts

  Finally, close this tab and all the previously opened terminal tabs and continue working in a new tab.
END
}

install_thoughtbot
install_apt
install_packages
install_binaries
run_script
install_ohmyzsh
install_spacevim
show_final_messages
